### ISSUE TITLE
和訳方法について wiki を使う提案

### ISSUE THREAD

**Issue by imamuray** [lean-ja/fp-lean-ja#22]
現状、「翻訳の際のルール」や「対訳表」がリポジトリのファイルとして管理されていますが、これらを Github の wiki で管理するとよいのではないかと考えました。
参考: [ウィキについて - GitHub Docs](https://docs.github.com/ja/communities/documenting-your-project-with-wikis/about-wikis)

メリット
- ルールや対訳表の更新をリポジトリにコミットすることなく素早く更新できる。
  - 例: ある PR で和訳作業中に新規に対訳表に追加したい単語があったとき、別の PR でも同じ単語が出てきた場合に wiki で対訳表を管理すればその単語の扱い方の共有がすぐにできる。

デメリット
- リポジトリだけでなく wiki の管理も発生する。

**Comment by Seasawher** [comment]
提案ありがとうございます

たしかにPRマージ前に対訳表の変更が見られるのは便利ですね．また対訳表はPRマージ時にコンフリクトが発生する主要な部分であり，対訳表がなければコンフリクトが発生しなくなるというメリットもありそうです．対訳表を wiki に移すのはいいかもしれません． 

wiki のアクセス権限の仕様は

> ウィキは、GitHub 上で直接編集することも、ウィキのファイルをローカルで編集することもできます。 デフォルトでは、リポジトリへの書き込みアクセス権を持つユーザのみが Wiki に変更を加えることができますが、GitHub.com のすべてのユーザがパブリック リポジトリの Wiki に貢献できるようにすることも可能です。

という風になっているようですが，運用するなら GitHub.com の全ユーザが編集できるようにしておくと便利かなと思いました．

@aconite-ac いかがでしょうか

**Comment by aconite-ac** [comment]
@imamuray @Seasawher

個人的には以下の2つの理由により、wiki で対訳表を管理するのはあまり得策ではないように思っています。
* 対訳表の編集権限者が多いと、編集権限者の中で訳語に対する合意が得られない可能性がある。
  * 訳語は文書の中で統一したい一方で、どの訳語を適切と考えるかは各個人の見解により異なりうると思っています。現在 `SUMMARY.md` と1章全体に登場する用語に絞って対訳表の原案を作成していますが、既存の翻訳と異なる訳語を当てたい単語や、訳語の決定について意見が分かれるであろう単語がすでにいくつかあります。
  * 各個人の見解を参考にしつつ訳語を統一するには、`GLOSSARY.md` に関するPRを出せる人をレビュアーに絞った上で、

    1. 訳者は個人の見解に基づき訳語を決めて翻訳する。
    2. レビュアーは訳文を参考にして `GLOSSARY.md` を更新し、それに基づいたレビューにより訳語を統一する。
    3. 全ユーザ向けに訳語提案用の issue を用意し、レビュアーが決定した訳語が不適切だと思った場合は、issue を通じて提案する。

    というプロセスを経るのがよいかなと思っています。
    このプロセスには、「翻訳時に訳語を統一する手間を省く」・「1つの単語に複数の訳語が与えられていた場合、それらを比較検討することでよりよい訳語決定に繋がるかもしれない」という2つのねらいがあります。
* コンフリクトを回避するためには、PR提出時点での訳語の統一より、「PRに含む変更は1節に限り、(翻訳・レビュー・修正に関わらず)各節について Open 中のPRは最大1つにする」といったルールの制定が効果的だと思われる。
  * (もしコンフリクトについて誤解がありそうでしたら、指摘していただけるとありがたいです……。)

前提として、対訳表は翻訳において非常に重要な要素だと考えており、
レビューする際はかなり細かく単語をピックアップし、注意深く訳語を検討したいと考えています。
まず翻訳ルールを再検討し、実際に上記のプロセスに則りレビューをしてみて、何か問題がありそうなら wiki を使う方法を含め再検討させていただきたいと思います。

(ただ、考えを詰め切れていない気もします……。対訳表と訳語決定プロセスについて、ご意見ありましたら伺いたく思います。)

**Comment by imamuray** [comment]
@Seasawher @aconite-ac 

検討ありがとうございます。

提案した手前ではありますが、私自身改めて考えてみて、wiki の有無よりも翻訳ルールや対訳表の更新がどのような手順で行われるかが明確になることが元々の問題意識としてあったと思います。
複数人が PR で和訳作業を進める中で、PR 間のコンフリクトを起こさず翻訳ルールや対訳表を更新する手段の一つとして wiki の利用があると考えます。そのため wiki を使用せず、権限を持った人が任意のタイミングで README や GLOSSARY を更新する方法も手段としてはありだと考えます。

@aconite-ac さんの提案は更新プロセスとしてよさそうだと思いました。

この issue 作成時の懸念点として、和訳 PR 作成者が対訳表の更新や訳語選びを意識して PR を出さなければいけないと考えていましたが、提案いただいた方法なら PR 作成者は一旦個人の見解で作業を進めることができ、対訳表の更新も検討したうえで更新されるので私が考えていた懸念点は解消できそうです。

**Comment by Seasawher** [comment]
問題ないと思います

**Comment by imamuray** [comment]
現状、wiki を使わないでも運用できそうではあるのでこの issue は一旦クローズでいいと思います。
