### ISSUE TITLE
対訳表への変更提案フォーム（廃止）

### ISSUE THREAD

**Issue by aconite-ac** [lean-ja/fp-lean-ja#35]
~~[対訳表](https://github.com/lean-ja/fp-lean-ja/blob/main/functional-programming-lean/GLOSSARY.md)への変更提案はこちらにお願いします。~~
~~提案の際は、~~

~~* 提案対象の用語~~
~~* 提案内容~~
~~* 提案理由~~

~~の3つをお書きください。~~
~~マージコンフリクトを避けるため、レビュアー以外の方が対訳表にPull Requestを出すことはお控えください。~~

対訳表への変更提案がある際は、「New issue」ボタンを押した後、issue template「対訳表への変更提案」をお使いください。

**Comment by Seasawher** [comment]
特定のissue にぶら下げるのではなく、issue_template を使用するのが一般的なアプローチだと思います。

**Comment by aconite-ac** [comment]
issue_template のご紹介ありがとうございます！
ご提案通り「訳の誤りの指摘」「対訳表への変更提案」「そのほか」のテンプレートを作成するのがよさそうですね。
テンプレートを作成して Pull Request を出しますので、お手数ですがreview のほどよろしくお願いいたします。
