### ISSUE TITLE
句読点を `、` と `。` に変更する

### ISSUE THREAD

**Issue by Seasawher** [lean-ja/fp-lean-ja#61]
[「公用文作成の考え方」](https://www.bunka.go.jp/seisaku/bunkashingikai/kokugo/hokoku/pdf/93651301_01.pdf) を改めて確認したところ，句読点には `、` と `。` を使うのが原則だと書かれていました．（昔はカンマとピリオドだった気がします）

エディタ上でも `、` と `。` の方が判読しやすくて統一しやすいというメリットがあるので，この機に句読点を変更したほうが良いかと思いました．

**Comment by Seasawher** [comment]
#24 での提案にも沿っています。

**Comment by aconite-ac** [comment]
ご提案ありがとうございます！
#24 では現行の方針との擦り合わせを考えましたが、元々自分の意見は今回のご提案と同様でしたので、賛成いたします。
方針変更の根拠も挙げていただいたもので十分だと思います。

**Comment by aconite-ac** [comment]
レビュアー間で合意が得られ、また訳者2名の方からリアクションを頂いたので、
句読点の変更に関する PR を作成しました。

PR がマージされ次第、Discordサーバ「LEAN-JA」上でも句読点の変更についてアナウンスいたします。
未レビューのファイルの句読点については、マージ済・未マージ問わずレビューの際に変更いたしますので、
訳者の方々が事前に変更する必要はありません。
